# Generated by Django 3.2.9 on 2021-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
